
stages:
#  - build
#  - tagged
  - website

# ===============================================
#    WEB SITE
# ===============================================

pages:
  stage: website
  image: node:13.5.0
  before_script: []
  script:
    - cd website
    - mkdir -p ../public
    - yarn install
    - yarn build
    # The build directory is created based on the value set for projectName in
    # website/siteConfig.js. If you change it there, you need to change it here
    # as well.
    - cp -R build/* ../public/
    - ls ../public
  artifacts:
    paths:
      - public
  only:
    - master
  when: manual
  environment:
    name: page
    url: https://kubernetes.pages.gitlab.si.francetelecom.fr/nifikop/