apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nifiusers.nifi.orange.com
  labels:
    app: {{ template "nifikop.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: nifi.orange.com
  names:
    kind: NifiUser
    listKind: NifiUserList
    plural: nifiusers
    singular: nifiuser
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Nifi User is the Schema for the nifi users API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: NifiUserSpec defines the desired state of NifiUser
          properties:
            clusterRef:
              description: ClusterReference states a reference to a cluster for topic/user
                provisioning
              properties:
                name:
                  type: string
                namespace:
                  type: string
              required:
                - name
              type: object
            dnsNames:
              items:
                type: string
              type: array
            includeJKS:
              description: TopicGrants []UserTopicGrant `json:"topicGrants,omitempty"`
              type: boolean
            secretName:
              type: string
          required:
            - clusterRef
            - secretName
          type: object
        status:
          description: NifiUserStatus defines the observed state of NifiUser
          properties:
            acls:
              items:
                type: string
              type: array
            state:
              description: UserState defines the state of a NifiUser
              type: string
          required:
            - state
          type: object
      type: object
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true